import sys

uses_feature_context = ["android.hardware.audio.low_latency", "android.hardware.audio.output",
                        "android.hardware.audio.pro", "android.hardware.microphone",
                        "android.hardware.bluetooth", "android.hardware.bluetooth_le",
                        "android.hardware.camera.any", "android.hardware.camera",
                        "android.hardware.camera.front", "android.hardware.camera.external",
                        "android.hardware.camera.autofocus", "android.hardware.camera.flash",
                        "android.hardware.camera.capability.manual_post_processing",
                        "android.hardware.camera.capability.manual_sensor",
                        "android.hardware.camera.capability.raw", "android.hardware.camera.level.full",
                        "android.hardware.type.automotive", "android.hardware.type.television",
                        "android.hardware.type.watch", "android.hardware.fingerprint",
                        "android.hardware.gamepad", "android.hardware.consumerir",
                        "android.hardware.location", "android.hardware.location.gps",
                        "android.hardware.location.network", "android.hardware.nfc", "android.hardware.nfc.hce",
                        "android.hardware.opengles.aep", "android.hardware.sensor.accelerometer",
                        "android.hardware.sensor.ambient_temperature", "android.hardware.sensor.barometer",
                        "android.hardware.sensor.compass", "android.hardware.sensor.gyroscope",
                        "android.hardware.sensor.hifi_sensors", "android.hardware.sensor.heartrate",
                        "android.hardware.sensor.heartrate.ecg", "android.hardware.sensor.light",
                        "android.hardware.sensor.proximity", "android.hardware.sensor.relative_humidity",
                        "android.hardware.sensor.stepcounter", "android.hardware.sensor.stepdetector",
                        "android.hardware.screen.landscape", "android.hardware.screen.portrait",
                        "android.hardware.telephony", "android.hardware.telephony.cdma",
                        "android.hardware.telephony.gsm", "android.hardware.faketouch",
                        "android.hardware.faketouch.multitouch.distinct",
                        "android.hardware.faketouch.multitouch.jazzhand",
                        "android.hardware.touchscreen", "android.hardware.touchscreen.multitouch",
                        "android.hardware.touchscreen.multitouch.distinct",
                        "android.hardware.touchscreen.multitouch.jazzhand", "android.hardware.usb.accessory",
                        "android.hardware.usb.host",
                        "android.hardware.vulkan.compute", "android.hardware.vulkan.level",
                        "android.hardware.vulkan.version", "android.hardware.wifi",
                        "android.hardware.wifi.direct",

                        # software features
                        "android.software.sip", "android.software.sip.voip", "android.software.webview",
                        "android.software.input_methods", "android.software.backup", "android.software.device_admin",
                        "android.software.managed_users", "android.software.securely_removes_users",
                        "android.software.verified_boot", "android.software.midi", "android.software.print",
                        "android.software.leanback", "android.software.live_tv", "android.software.app_widgets",
                        "android.software.home_screen", "android.software.live_wallpaper"]

install_permissions = [("android.permission.ACCESS_LOCATION_EXTRA_COMMANDS", (1, sys.maxsize)),
                       ("android.permission.ACCESS_NETWORK_STATE", (1, sys.maxsize)),
                       ("android.permission.ACCESS_NOTIFICATION_POLICY",
                        (23, sys.maxsize)),
                       ("android.permission.ACCESS_WIFI_STATE", (1, sys.maxsize)),
                       ("android.permission.BLUETOOTH", (1, sys.maxsize)),
                       ("android.permission.BLUETOOTH_ADMIN", (1, sys.maxsize)),
                       ("android.permission.BROADCAST_STICKY", (1, sys.maxsize)),
                       ("android.permission.CALL_COMPANION_APP", (29, sys.maxsize)),
                       ("android.permission.CHANGE_NETWORK_STATE", (1, sys.maxsize)),
                       ("android.permission.CHANGE_WIFI_MULTICAST_STATE",
                        (4, sys.maxsize)),
                       ("android.permission.CHANGE_WIFI_STATE", (1, sys.maxsize)),
                       ("android.permission.DELIVER_COMPANION_MESSAGES",
                        (33, sys.maxsize)),
                       ("android.permission.DISABLE_KEYGUARD", (1, sys.maxsize)),
                       ("android.permission.EXPAND_STATUS_BAR", (1, sys.maxsize)),
                       ("android.permission.FOREGROUND_SERVICE", (28, sys.maxsize)),
                       ("android.permission.GET_PACKAGE_SIZE", (1, sys.maxsize)),
                       ("android.permission.GET_TASKS", (1, 21)),
                       ("android.permission.HIDE_OVERLAY_WINDOWS", (31, sys.maxsize)),
                       ("android.permission.HIGH_SAMPLING_RATE_SENSORS",
                        (31, sys.maxsize)),
                       ("com.android.launcher.permission.INSTALL_SHORTCUT",
                        (19, sys.maxsize)),
                       ("android.permission.INTERNET", (1, sys.maxsize)),
                       ("android.permission.KILL_BACKGROUND_PROCESSES", (8, sys.maxsize)),
                       ("android.permission.LAUNCH_MULTI_PANE_SETTINGS_DEEP_LINK",
                        (32, sys.maxsize)),
                       ("android.permission.MANAGE_OWN_CALLS", (26, sys.maxsize)),
                       ("android.permission.MODIFY_AUDIO_SETTINGS", (1, sys.maxsize)),
                       ("android.permission.NFC", (9, sys.maxsize)),
                       ("android.permission.NFC_PREFERRED_PAYMENT_INFO",
                        (30, sys.maxsize)),
                       ("android.permission.NFC_TRANSACTION_EVENT", (28, sys.maxsize)),
                       ("android.permission.PERSISTENT_ACTIVITY", (1, 15)),
                       ("android.permission.QUERY_ALL_PACKAGES", (30, sys.maxsize)),
                       ("android.permission.READ_ASSISTANT_APP_SEARCH_DATA",
                        (33, sys.maxsize)),
                       ("android.permission.READ_BASIC_PHONE_STATE", (33, sys.maxsize)),
                       ("android.permission.READ_HOME_APP_SEARCH_DATA",
                        (33, sys.maxsize)),
                       ("android.permission.READ_SYNC_SETTINGS", (1, sys.maxsize)),
                       ("android.permission.READ_SYNC_STATS", (1, sys.maxsize)),
                       ("android.permission.RECEIVE_BOOT_COMPLETED", (1, sys.maxsize)),
                       ("android.permission.REORDER_TASKS", (1, sys.maxsize)),
                       ("android.permission.REQUEST_COMPANION_PROFILE_WATCH",
                        (31, sys.maxsize)),
                       ("android.permission.REQUEST_COMPANION_RUN_IN_BACKGROUND",
                        (26, sys.maxsize)),
                       ("android.permission.REQUEST_COMPANION_SELF_MANAGED",
                        (33, sys.maxsize)),
                       ("android.permission.REQUEST_COMPANION_START_FOREGROUND_SERVICES_FROM_BACKGROUND",
                        (31, sys.maxsize)),
                       ("android.permission.REQUEST_COMPANION_USE_DATA_IN_BACKGROUND",
                        (26, sys.maxsize)),
                       ("android.permission.REQUEST_DELETE_PACKAGES", (26, sys.maxsize)),
                       ("android.permission.REQUEST_IGNORE_BATTERY_OPTIMIZATIONS",
                        (23, sys.maxsize)),
                       ("android.permission.REQUEST_OBSERVE_COMPANION_DEVICE_PRESENCE",
                        (31, sys.maxsize)),
                       ("android.permission.REQUEST_PASSWORD_COMPLEXITY",
                        (29, sys.maxsize)),
                       ("android.permission.RESTART_PACKAGES", (1, 15)),
                       ("android.permission.SCHEDULE_EXACT_ALARM", (31, sys.maxsize)),
                       ("com.android.alarm.permission.SET_ALARM", (9, sys.maxsize)),
                       ("android.permission.SET_WALLPAPER", (1, sys.maxsize)),
                       ("android.permission.SET_WALLPAPER_HINTS", (1, sys.maxsize)),
                       ("android.permission.SUBSCRIBE_TO_KEYGUARD_LOCKED_STATE",
                        (33, sys.maxsize)),
                       ("android.permission.SYSTEM_ALERT_WINDOW", (1, sys.maxsize)),
                       ("android.permission.TRANSMIT_IR", (19, sys.maxsize)),
                       ("com.android.launcher.permission.UNINSTALL_SHORTCUT",
                        (19, sys.maxsize)),
                       ("android.permission.UPDATE_PACKAGES_WITHOUT_USER_ACTION",
                        (31, sys.maxsize)),
                       ("android.permission.USE_BIOMETRIC", (28, sys.maxsize)),
                       ("android.permission.USE_EXACT_ALARM", (33, sys.maxsize)),
                       ("android.permission.USE_FINGERPRINT", (23, 28)),
                       ("android.permission.USE_FULL_SCREEN_INTENT", (29, sys.maxsize)),
                       ("android.permission.VIBRATE", (1, sys.maxsize)),
                       ("android.permission.WAKE_LOCK", (1, sys.maxsize)),
                       ("android.permission.WRITE_SYNC_SETTINGS", (1, sys.maxsize))]

runtime_permissions = [("android.permission.ACCEPT_HANDOVER", (28, sys.maxsize)),
                       ("android.permission.ACCESS_BACKGROUND_LOCATION",
                        (29, sys.maxsize)),
                       ("android.permission.ACCESS_COARSE_LOCATION", (1, sys.maxsize)),
                       ("android.permission.ACCESS_FINE_LOCATION", (1, sys.maxsize)),
                       ("android.permission.ACCESS_MEDIA_LOCATION", (29, sys.maxsize)),
                       ("android.permission.ACTIVITY_RECOGNITION", (29, sys.maxsize)),
                       ("com.android.voicemail.permission.ADD_VOICEMAIL",
                        (14, sys.maxsize)),
                       ("android.permission.ANSWER_PHONE_CALLS", (26, sys.maxsize)),
                       ("android.permission.BLUETOOTH_ADVERTISE", (31, sys.maxsize)),
                       ("android.permission.BLUETOOTH_CONNECT", (31, sys.maxsize)),
                       ("android.permission.BLUETOOTH_SCAN", (31, sys.maxsize)),
                       ("android.permission.BODY_SENSORS", (20, sys.maxsize)),
                       ("android.permission.BODY_SENSORS_BACKGROUND", (33, sys.maxsize)),
                       ("android.permission.CALL_PHONE", (1, sys.maxsize)),
                       ("android.permission.CAMERA", (1, sys.maxsize)),
                       ("android.permission.GET_ACCOUNTS", (1, sys.maxsize)),
                       ("android.permission.NEARBY_WIFI_DEVICES", (1, sys.maxsize)),
                       ("android.permission.POST_NOTIFICATIONS", (33, sys.maxsize)),
                       ("android.permission.PROCESS_OUTGOING_CALLS", (1, 29)),
                       ("android.permission.READ_CALENDAR", (1, sys.maxsize)),
                       ("android.permission.READ_CALL_LOG", (16, sys.maxsize)),
                       ("android.permission.READ_CONTACTS", (1, sys.maxsize)),
                       ("android.permission.READ_EXTERNAL_STORAGE", (16, sys.maxsize)),
                       ("android.permission.READ_MEDIA_AUDIO", (33, sys.maxsize)),
                       ("android.permission.READ_MEDIA_IMAGES", (33, sys.maxsize)),
                       ("android.permission.READ_MEDIA_VIDEO", (33, sys.maxsize)),
                       ("android.permission.READ_PHONE_NUMBERS", (26, sys.maxsize)),
                       ("android.permission.READ_PHONE_STATE", (1, sys.maxsize)),
                       ("android.permission.READ_SMS", (1, sys.maxsize)),
                       ("android.permission.RECEIVE_MMS", (1, sys.maxsize)),
                       ("android.permission.RECEIVE_SMS", (1, sys.maxsize)),
                       ("android.permission.RECEIVE_WAP_PUSH", (1, sys.maxsize)),
                       ("android.permission.RECORD_AUDIO", (1, sys.maxsize)),
                       ("android.permission.SEND_SMS", (1, sys.maxsize)),
                       ("android.permission.USE_SIP", (9, sys.maxsize)),
                       ("android.permission.UWB_RANGING", (31, sys.maxsize)),
                       ("android.permission.WRITE_CALENDAR", (1, sys.maxsize)),
                       ("android.permission.WRITE_CALL_LOG", (16, sys.maxsize)),
                       ("android.permission.WRITE_CONTACTS", (1, sys.maxsize)),
                       ("android.permission.WRITE_EXTERNAL_STORAGE", (4, sys.maxsize)),
                       ]

protected_permissions = [("android.permission.ACCESS_BLOBS_ACROSS_USERS", (31, sys.maxsize)),
                         ("android.permission.ACCESS_CHECKIN_PROPERTIES",
                          (1, sys.maxsize)),
                         ("android.permission.ACCOUNT_MANAGER", (5, sys.maxsize)),
                         ("android.permission.BATTERY_STATS", (1, sys.maxsize)),
                         ("android.permission.BIND_ACCESSIBILITY_SERVICE",
                          (16, sys.maxsize)),
                         ("android.permission.BIND_APPWIDGET", (3, sys.maxsize)),
                         ("android.permission.BIND_AUTOFILL_SERVICE", (26, sys.maxsize)),
                         ("android.permission.BIND_CALL_REDIRECTION_SERVICE",
                          (29, sys.maxsize)),
                         ("android.permission.BIND_CARRIER_MESSAGING_CLIENT_SERVICE",
                          (29, sys.maxsize)),
                         ("android.permission.BIND_CARRIER_MESSAGING_SERVICE", (22, 23)),
                         ("android.permission.BIND_CARRIER_SERVICES", (23, sys.maxsize)),
                         ("android.permission.BIND_CHOOSER_TARGET_SERVICE", (23, 30)),
                         ("android.permission.BIND_COMPANION_DEVICE_SERVICE",
                          (31, sys.maxsize)),
                         ("android.permission.BIND_CONDITION_PROVIDER_SERVICE",
                          (24, sys.maxsize)),
                         ("android.permission.BIND_CONTROLS", (30, sys.maxsize)),
                         ("android.permission.BIND_DEVICE_ADMIN", (8, sys.maxsize)),
                         ("android.permission.BIND_DREAM_SERVICE", (21, sys.maxsize)),
                         ("android.permission.BIND_INCALL_SERVICE", (23, sys.maxsize)),
                         ("android.permission.BIND_INPUT_METHOD", (3, sys.maxsize)),
                         ("android.permission.BIND_MIDI_DEVICE_SERVICE",
                          (23, sys.maxsize)),
                         ("android.permission.BIND_NFC_SERVICE", (19, sys.maxsize)),
                         ("android.permission.BIND_NOTIFICATION_LISTENER_SERVICE",
                          (18, sys.maxsize)),
                         ("android.permission.BIND_PRINT_SERVICE", (19, sys.maxsize)),
                         ("android.permission.BIND_QUICK_ACCESS_WALLET_SERVICE",
                          (30, sys.maxsize)),
                         ("android.permission.BIND_QUICK_SETTINGS_TILE",
                          (24, sys.maxsize)),
                         ("android.permission.BIND_REMOTEVIEWS", (11, sys.maxsize)),
                         ("android.permission.BIND_SCREENING_SERVICE",
                          (24, sys.maxsize)),
                         ("android.permission.BIND_TELECOM_CONNECTION_SERVICE",
                          (23, sys.maxsize)),
                         ("android.permission.BIND_TEXT_SERVICE", (14, sys.maxsize)),
                         ("android.permission.BIND_TV_INPUT", (21, sys.maxsize)),
                         ("android.permission.BIND_TV_INTERACTIVE_APP",
                          (33, sys.maxsize)),
                         ("android.permission.BIND_VISUAL_VOICEMAIL_SERVICE",
                          (26, sys.maxsize)),
                         ("android.permission.BIND_VOICE_INTERACTION",
                          (21, sys.maxsize)),
                         ("android.permission.BIND_VPN_SERVICE", (14, sys.maxsize)),
                         ("android.permission.BIND_VR_LISTENER_SERVICE",
                          (24, sys.maxsize)),
                         ("android.permission.BIND_WALLPAPER", (8, sys.maxsize)),
                         ("android.permission.BLUETOOTH_PRIVILEGED", (19, sys.maxsize)),
                         ("android.permission.BROADCAST_PACKAGE_REMOVED",
                          (1, sys.maxsize)),
                         ("android.permission.BROADCAST_SMS", (2, sys.maxsize)),
                         ("android.permission.BROADCAST_WAP_PUSH", (2, sys.maxsize)),
                         ("android.permission.CALL_PRIVILEGED", (1, sys.maxsize)),
                         ("android.permission.CAPTURE_AUDIO_OUTPUT", (19, sys.maxsize)),
                         ("android.permission.CHANGE_COMPONENT_ENABLED_STATE",
                          (1, sys.maxsize)),
                         ("android.permission.CHANGE_CONFIGURATION", (1, sys.maxsize)),
                         ("android.permission.CLEAR_APP_CACHE", (1, sys.maxsize)),
                         ("android.permission.CONTROL_LOCATION_UPDATES",
                          (1, sys.maxsize)),
                         ("android.permission.DELETE_CACHE_FILES", (1, sys.maxsize)),
                         ("android.permission.DELETE_PACKAGES", (1, sys.maxsize)),
                         ("android.permission.DIAGNOSTIC", (1, sys.maxsize)),
                         ("android.permission.DUMP", (1, sys.maxsize)),
                         ("android.permission.FACTORY_TEST", (1, sys.maxsize)),
                         ("android.permission.GET_ACCOUNTS_PRIVILEGED",
                          (23, sys.maxsize)),
                         ("android.permission.GLOBAL_SEARCH", (4, sys.maxsize)),
                         ("android.permission.INSTALL_LOCATION_PROVIDER",
                          (4, sys.maxsize)),
                         ("android.permission.INSTALL_PACKAGES", (1, sys.maxsize)),
                         ("android.permission.INSTANT_APP_FOREGROUND_SERVICE",
                          (26, sys.maxsize)),
                         ("android.permission.INTERACT_ACROSS_PROFILES",
                          (30, sys.maxsize)),
                         ("android.permission.LOADER_USAGE_STATS", (30, sys.maxsize)),
                         ("android.permission.LOCATION_HARDWARE", (18, sys.maxsize)),
                         ("android.permission.MANAGE_DOCUMENTS", (19, sys.maxsize)),
                         ("android.permission.MANAGE_EXTERNAL_STORAGE",
                          (30, sys.maxsize)),
                         ("android.permission.MANAGE_MEDIA", (31, sys.maxsize)),
                         ("android.permission.MANAGE_ONGOING_CALLS", (31, sys.maxsize)),
                         ("android.permission.MANAGE_WIFI_INTERFACES",
                          (33, sys.maxsize)),
                         ("android.permission.MANAGE_WIFI_NETWORK_SELECTION",
                          (33, sys.maxsize)),
                         ("android.permission.MASTER_CLEAR", (1, sys.maxsize)),
                         ("android.permission.MEDIA_CONTENT_CONTROL", (19, sys.maxsize)),
                         ("android.permission.MODIFY_PHONE_STATE", (1, sys.maxsize)),
                         ("android.permission.MOUNT_FORMAT_FILESYSTEMS",
                          (3, sys.maxsize)),
                         ("android.permission.MOUNT_UNMOUNT_FILESYSTEMS",
                          (1, sys.maxsize)),
                         ("android.permission.OVERRIDE_WIFI_CONFIG", (33, sys.maxsize)),
                         ("android.permission.PACKAGE_USAGE_STATS", (23, sys.maxsize)),
                         ("android.permission.READ_INPUT_STATE", (1, 16)),
                         ("android.permission.READ_LOGS", (1, sys.maxsize)),
                         ("android.permission.READ_NEARBY_STREAMING_POLICY",
                          (33, sys.maxsize)),
                         ("android.permission.READ_PRECISE_PHONE_STATE",
                          (30, sys.maxsize)),
                         ("com.android.voicemail.permission.READ_VOICEMAIL",
                          (21, sys.maxsize)),
                         ("android.permission.REBOOT", (1, sys.maxsize)),
                         ("android.permission.REQUEST_COMPANION_PROFILE_APP_STREAMING",
                          (33, sys.maxsize)),
                         ("android.permission.REQUEST_COMPANION_PROFILE_AUTOMOTIVE_PROJECTION",
                          (33, sys.maxsize)),
                         ("android.permission.REQUEST_COMPANION_PROFILE_COMPUTER",
                          (33, sys.maxsize)),
                         ("android.permission.REQUEST_INSTALL_PACKAGES",
                          (23, sys.maxsize)),
                         ("android.permission.SEND_RESPOND_VIA_MESSAGE",
                          (18, sys.maxsize)),
                         ("android.permission.SET_ALWAYS_FINISH", (1, sys.maxsize)),
                         ("android.permission.SET_ANIMATION_SCALE", (1, sys.maxsize)),
                         ("android.permission.SET_DEBUG_APP", (1, sys.maxsize)),
                         ("android.permission.SET_PREFERRED_APPLICATIONS", (1, 15)),
                         ("android.permission.SET_PROCESS_LIMIT", (1, sys.maxsize)),
                         ("android.permission.SET_TIME", (8, sys.maxsize)),
                         ("android.permission.SET_TIME_ZONE", (1, sys.maxsize)),
                         ("android.permission.SIGNAL_PERSISTENT_PROCESSES",
                          (1, sys.maxsize)),
                         ("android.permission.SMS_FINANCIAL_TRANSACTIONS", (29, 31)),
                         ("android.permission.START_FOREGROUND_SERVICES_FROM_BACKGROUND",
                          (31, sys.maxsize)),
                         ("android.permission.START_VIEW_APP_FEATURES",
                          (33, sys.maxsize)),
                         ("android.permission.START_VIEW_PERMISSION_USAGE",
                          (29, sys.maxsize)),
                         ("android.permission.STATUS_BAR", (1, sys.maxsize)),
                         ("android.permission.UPDATE_DEVICE_STATS", (3, sys.maxsize)),
                         ("android.permission.USE_ICC_AUTH_WITH_DEVICE_IDENTIFIER",
                          (31, sys.maxsize)),
                         ("android.permission.WRITE_APN_SETTINGS", (1, sys.maxsize)),
                         ("android.permission.WRITE_GSERVICES", (1, sys.maxsize)),
                         ("android.permission.WRITE_SECURE_SETTINGS", (3, sys.maxsize)),
                         ("android.permission.WRITE_SETTINGS", (1, sys.maxsize)),
                         ("com.android.voicemail.permission.WRITE_VOICEMAIL", (21, sys.maxsize))]

uses_permission_context = install_permissions + protected_permissions

standard_activity_intent = [("android.intent.action.VIEW", (1, sys.maxsize)),
                            ("android.intent.action.ATTACH_DATA", (1, sys.maxsize)),
                            ("android.intent.action.EDIT", (1, sys.maxsize)),
                            ("android.intent.action.PICK", (1, sys.maxsize)),
                            ("android.intent.action.CHOOSER", (1, sys.maxsize)),
                            ("android.intent.action.GET_CONTENT", (1, sys.maxsize)),
                            ("android.intent.action.DIAL", (1, sys.maxsize)),
                            ("android.intent.action.CALL", (1, sys.maxsize)),
                            ("android.intent.action.SEND", (1, sys.maxsize)),
                            ("android.intent.action.SENDTO", (1, sys.maxsize)),
                            ("android.intent.action.ANSWER", (1, sys.maxsize)),
                            ("android.intent.action.INSERT", (1, sys.maxsize)),
                            ("android.intent.action.DELETE", (1, sys.maxsize)),
                            ("android.intent.action.RUN", (1, sys.maxsize)),
                            ("android.intent.action.SYNC", (1, sys.maxsize)),
                            ("android.intent.action.PICK_ACTIVITY", (1, sys.maxsize)),
                            ("android.intent.action.SEARCH", (1, sys.maxsize)),
                            ("android.intent.action.WEB_SEARCH", (1, sys.maxsize)),
                            ("android.intent.action.FACTORY_TEST", (1, sys.maxsize))]

standard_broadcast_intent = [("android.intent.action.TIME_TICK", (1, sys.maxsize)),
                             ("android.intent.action.TIME_SET", (1, sys.maxsize)),
                             ("android.intent.action.TIMEZONE_CHANGED",
                              (1, sys.maxsize)),
                             ("android.intent.action.BOOT_COMPLETED", (1, sys.maxsize)),
                             ("android.intent.action.PACKAGE_ADDED", (1, sys.maxsize)),
                             ("android.intent.action.PACKAGE_CHANGED",
                              (1, sys.maxsize)),
                             ("android.intent.action.PACKAGE_REMOVED",
                              (1, sys.maxsize)),
                             ("android.intent.action.PACKAGE_RESTARTED",
                              (1, sys.maxsize)),
                             ("android.intent.action.PACKAGE_DATA_CLEARED",
                              (3, sys.maxsize)),
                             ("android.intent.action.PACKAGES_SUSPENDED",
                              (24, sys.maxsize)),
                             ("android.intent.action.PACKAGES_UNSUSPENDED",
                              (24, sys.maxsize)),
                             ("android.intent.action.UID_REMOVED", (1, sys.maxsize)),
                             ("android.intent.action.BATTERY_CHANGED",
                              (1, sys.maxsize)),
                             ("android.intent.action.ACTION_POWER_CONNECTED",
                              (4, sys.maxsize)),
                             ("android.intent.action.ACTION_POWER_DISCONNECTED",
                              (4, sys.maxsize)),
                             ("android.intent.action.ACTION_SHUTDOWN", (4, sys.maxsize))]

standard_category = [("android.intent.category.DEFAULT", (1, sys.maxsize)),
                     ("android.intent.category.BROWSABLE", (1, sys.maxsize)),
                     ("android.intent.category.TAB", (1, sys.maxsize)),
                     ("android.intent.category.ALTERNATIVE", (1, sys.maxsize)),
                     ("android.intent.category.SELECTED_ALTERNATIVE", (1, sys.maxsize)),
                     ("android.intent.category.LAUNCHER", (1, sys.maxsize)),
                     ("android.intent.category.INFO", (3, sys.maxsize)),
                     ("android.intent.category.HOME", (1, sys.maxsize)),
                     ("android.intent.category.PREFERENCE", (1, sys.maxsize)),
                     ("android.intent.category.TEST", (1, sys.maxsize)),
                     ("android.intent.category.CAR_DOCK", (5, sys.maxsize)),
                     ("android.intent.category.DESK_DOCK", (5, sys.maxsize)),
                     ("android.intent.category.LE_DESK_DOCK", (11, sys.maxsize)),
                     ("android.intent.category.HE_DESK_DOCK", (11, sys.maxsize)),
                     ("android.intent.category.CAR_MODE", (8, sys.maxsize)),
                     ("android.intent.category.APP_MARKET", (11, sys.maxsize)),
                     ("android.intent.category.VR_HOME", (26, sys.maxsize))]

intent_context = standard_activity_intent + \
    standard_broadcast_intent + standard_category
